name: Stable Development Build

on:
 push:
    paths:
      - SBRW.Launcher.RunTime/InsiderKit/**
 
jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 15
    steps:
    - name: Branch Checkout
      uses: actions/checkout@v3.3.0
    - name: Set Custom NuGet Packages
      run: |
        dotnet nuget add source "https://nuget.pkg.github.com/DavidCarbon-SBRW/index.json" -n "SBRW Launcher Libraries" -u ${env:UserName} -p ${env:Password} --store-password-in-clear-text
      env:
        UserName: ${{ github.repository_owner }}
        Password: ${{ secrets.GITHUB_TOKEN }}
    - name: Restore Custom NuGet Packages
      run: dotnet restore --ignore-failed-sources
    - name: Compile Windows Build
      run: dotnet build --configuration Release
    - name: Compile Unix Build
      run: dotnet build --configuration Release.Unix
    - name: Upload Windows Build Artifacts
      uses: actions/upload-artifact@v3.1.2
      with:
        name: Release
        path: |
          ${{ github.workspace }}/SBRW.Launcher.Net/bin/Release/*
        if-no-files-found: error
    - name: Upload Unix Build Artifacts
      uses: actions/upload-artifact@v3.1.2
      with:
        name: Unix.Release
        path: |
          ${{ github.workspace }}/SBRW.Launcher.Net/bin/Release.Unix/*
        if-no-files-found: error          