name: Stable Development Build

on:
 push:
    paths:
      - SBRW.Launcher.RunTime/InsiderKit/**
 
jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 15
    steps:
    - name: Branch Checkout
      uses: actions/checkout@v2.4.0
    - name: Setup .Net 6 SDK
      uses: actions/setup-dotnet@v1.9.0
      with:
        dotnet-version: '6.0.x'
    - name: Set Custom NuGet Packages
      run: |
        dotnet nuget add source "https://nuget.pkg.github.com/DavidCarbon-SBRW/index.json" -n "SBRW Launcher Libraries" -u ${env:UserName} -p ${env:Password} --store-password-in-clear-text
      env:
        UserName: ${{ secrets.GITHUB_USERNAME }}
        Password: ${{ secrets.GITHUB_TOKEN }}
    - name: Restore Custom NuGet Packages
      run: dotnet restore --ignore-failed-sources
    - name: Build Project
      run: dotnet build --configuration Release
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v2.2.4
      with:
        name: Release_GitHub_Actions
        path: |
          ${{ github.workspace }}/SBRW.Launcher.Net/bin/Release/*